### PR TITLE
Optimising webpack build

### PR DESCRIPTION
**Pull request by anthonygore**
I've been able to minimise your build file to about 113KBs

### CODE REVIEW

**Comment by kartsims** [comment]
Sweet! Thanks man, great work 💯 

It's strange though that we can't go below 113kB given that (Vue.js minifed](https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.6/vue.min.js) is 27.5kB, [vue-custom-element](https://github.com/karol-f/vue-custom-element/blob/master/dist/vue-custom-element.min.js) is 8kB and my custom code is quite light.

27.5 + 8 + a few extra for the custom component = 35.5kB+

Still a bit far from the 113kB

Weird... There seems to be more room for optimization !

Note : I disabled the sourcemap by default.

**Comment by anthonygore** [comment]
vue.min is only 27.7kbs when served gzipped from a CDN. If you look at the vue.min source it's actually about 75kbs.

I've submitted another pull request which gets the size down to 90kbs. If you inspect the webpack build, you'll see you really cant get any smaller than that because it just includes webpack bootstrap code, vue, vue-customelement and the bundled up custom code.

**Comment by anthonygore** [comment]
Btw if you compress the output file it goes down to about 31kbs, so that's the kind of size you could serve it at in production ;)

**Comment by kartsims** [comment]
You are absolutely right I didn't pay attention. Thanks for the input !

**Comment by kartsims** [comment]
I'll update the post in a few minutes

**Pull request merged**
